if (WIN32 OR WIN64)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        message(STATUS "Using Clang variant: ${CMAKE_CXX_COMPILER_FRONTEND_VARIANT}")
        set(CMAKE_CXX_IS_CLANG_WIN TRUE CACHE STRING "CMAKE_CXX_IS_CLANG_WIN" FORCE)
        if (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
            # using clang with cl front end
            set(CMAKE_CXX_IS_CLANG_CL TRUE CACHE STRING "CMAKE_CXX_IS_CLANG_CL" FORCE)
        elseif (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU")
            # using clang with regular front end
            if (CMAKE_CXX_SIMULATE_ID STREQUAL "MSVC")
                set(CMAKE_CXX_IS_CLANG_CL_GNU TRUE CACHE STRING "CMAKE_CXX_IS_CLANG_CL_GNU" FORCE)
            else()
                set(CMAKE_CXX_IS_CLANG_GNU TRUE CACHE STRING "CMAKE_CXX_IS_CLANG_GNU" FORCE)
            endif()
        else()
            message(WARNING "Unknown front variant for the Clang instance.")
        endif()
    endif()
endif()